name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
 #       dotnet-version: 5.0.101
        dotnet-version: 8.0.14
    - name: Install dependencies
      run: dotnet restore
    - name: Clean
      run: dotnet clean
    - name: Build
      run: dotnet publish -c release -o ./dist
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
